export const doctorDetails = [
  {
    state: "Bihar",
    district: "East Champaran",
    place: "Ruphara",
    name: "Dr. Kumar Surya Dev Prasad Yadav",
    contact: "7272940400",
  },
  {
    state: "Bihar",
    district: "East Champaran",
    place: "Shreerampur",
    name: "Dr. Hakim Prasad Mr. Krishna Dec Prasad",
    contact: "6205574939",
  },
  {
    state: "Bihar",
    district: "East Champaran",
    place: "Shreerampur",
    name: "Dr. Priyanka Kumari Hakim Prasad",
    contact: "7485025894",
  },
  {
    state: "Bihar",
    district: "Gaya",
    place: "Gaya",
    name: "Dr. Barich GK",
    contact: "9934749636",
  },
  {
    state: "Bihar",
    district: "Gaya",
    place: "Gaya",
    name: "Dr. Mrityunjay Kumar",
    contact: "9431290006",
  },
  {
    state: "Bihar",
    district: "Gopalganj",
    place: "Sirisiya Sasumusa Gopalganj",
    name: "Dr. Anwar Abdul Nazir",
    contact: "7004414451",
  },
  {
    state: "Bihar",
    district: "Rotas",
    place: "Dehri",
    name: "Dr. Ray Pratibha Krishna",
    contact: "N.A.",
  },
  {
    state: "Bihar",
    district: "Rotas",
    place: "Dehri",
    name: "Dr. Asif Anwar",
    contact: "9097956802",
  },
  {
    state: "Bihar",
    district: "West Champaran",
    place: "Valmiki Nagar",
    name: "Dr. Lakshamn Kumar",
    contact: "9199940929",
  },
  {
    state: "Delhi",
    district: "East Delhi",
    place: "Delhi",
    name: "Dr. Gupta Dr. Rashmi Rajesh KUmar",
    contact: "9868168384",
  },
  {
    state: "Delhi",
    district: "New Delhi",
    place: "New Delhi",
    name: "Dr. Gupta Manhorlal Hazari Lal",
    contact: "9650459393",
  },
  {
    state: "Delhi",
    district: "South West Delhi",
    place: "Vikaspur",
    name: "Dr. Gupta Manhorlal Hazari Lal",
    contact: "9810052126",
  },
  {
    state: "Delhi",
    district: "West Delhi",
    place: "Rajnagar",
    name: "Dr. Patel Kanchna Sanjeet Kumar",
    contact: "9350115775",
  },
  {
    state: "Haryana",
    district: "Panipat",
    place: "Babail",
    name: "Dr. Phaugat Anju",
    contact: "N.A.",
  },
  {
    state: "Haryana",
    district: "Yamunanagar",
    place: "Jagadhari",
    name: "Dr. Garg Amit & Team",
    contact: "9466017910",
  },
  {
    state: "Haryana",
    district: "Pakur",
    place: "Baliadangal, Maheshpur",
    name: "Dr. Alam Md Maqsud Md HussIN",
    contact: "7070604020",
  },
];
